name: ProtectingWolf
main: de.sunaru.ProtectingWolf.ProtectingWolf
version: 0.3.0
author: h4rvk4
commands:
  pwolf:
    description: Modify ProtectingWolf configuration settings.
    usage: /<command>
